version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:<tag>
    environment:
      MYSQL_DATABASE: "devops"         # Replace with your "database name"
      MYSQL_ROOT_PASSWORD: "root"    # Replace with your "database root password"
      MYSQL_USER: "deepesh"             # Replace with your "database user"
      MYSQL_PASSWORD: "root" # Replace with your "database user-password"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data: /var/lib/mysql       # volume storage path
    networks:
      - two-tier # Replace with your network name in which to create databse container
  flask:
    build:
      context: .                         # path of dockerfile in git repo
      dockerfile: Dockerfile             # Name of dockerfile in git repo
    container_name: two-tier-backend     # Replace with your "app-container-name"
    ports:
    - "5000:5000"
    environment:                      # environment variables take from app code
      MYSQL_HOST: mysql
      MYSQL_DB: devops
      MYSQL_USER: deepesh
      MYSQL_PASSWORD: root
    networks:
      - two-tier

volumes:
  mysql_data

networks:
  two-tier
  